version: '3.9'
services:
  php-apache:
    container_name: php-apache
    build: .
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80
    environment:
      POSTGRES_HOST: pg_server
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      JWT_SECRET: secret123
      JWT_EXP_TIME: 3600

  pg_server:
    container_name: pg_server
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg/data:/var/lib/postgresql/data
