version: '3.9'
services:
  php-apache:
    container_name: php-apache
    build: .
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80
    environment:
      POSTGRES_HOST: pg_server
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pg_server:
    container_name: pg_server
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg/data:/var/lib/postgresql/data

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5000:80
    volumes:
      - ./pg/pgadmin:/var/lib/pgadmin
